version: '2'
services:
  web:
    restart: on-failure
    build:
        context: .
        args:
            PYTHON_VERSION: 3.8.7
    environment:
      - REDIS=redis://10.114.0.2:6379/0
      - REDIS_CELERY=redis://10.114.0.2:6379/1
      - MONGO=mongodb://10.114.0.2:27017/
    volumes:
      - ./graphs.txt:/tmp/graphs.txt
    command: gunicorn -w 4 -b 0.0.0.0:8000 --log-level warning app:app
    ports:
      - "8088:8000"
    depends_on:
     - celery
  celery:
    restart: always
    build:
        context: .
        args:
            PYTHON_VERSION: 3.8.7
    environment:
      - REDIS=redis://10.114.0.2:6379/0
      - REDIS_CELERY=redis://10.114.0.2:6379/1
      - MONGO=mongodb://10.114.0.2:27017/
    command: celery -A tsa.celery worker -l warning -Q high_priority,default,query,low_priority -c 4
  beat:
    restart: always
    build:
        context: .
        args:
            PYTHON_VERSION: 3.8.7
    environment:
      - REDIS=redis://10.114.0.2:6379/0
      - REDIS_CELERY=redis://10.114.0.2:6379/1
      - MONGO=mongodb://10.114.0.2:27017/
    command: celery -A tsa.celery beat -l warning
